### ISSUE TITLE
Irish 1998 team missing

### ISSUE THREAD

**Issue by ocfnash** [abeakkas/ipho-unofficial.org#3]
I just came across this lovely project and noticed that you do not have data for Ireland's participation in 1998 (the first year that Ireland participated in fact).

Here are the names of the team that represented Ireland in Iceland in 1998 (in alphabetical order):
 * Charlotte Conn
 * Peter Harper
 * Andrew McDonough
 * Oliver Nash [me]
 * Ben O'Leary

Unfortunately I do not have any record of where we ranked except that I recall none of us managed to earn an honourable mention or a medal.

The delegation leader was [Enda McGlynn](http://www.dcu.ie/physics/people/enda-mcglynn.shtml).

**Comment by abeakkas** [comment]
Thank you very much for the info! I've updated the website:
http://ipho-unofficial.org/timeline/1998/individual

-Abe

**Comment by ocfnash** [comment]
Thanks!
